### PR TITLE
Don't display protocol inscriptions on homepage

### LINKED ISSUE #2659: Hide BRC-20 inscriptions from homepage
BRC-20s make the homepage look pretty ugly, we should probably figure out a way to hide them. This wouldn't change whether they're indexed or not, or whether you can look them up by inscription ID or number, just whether or not you can see them on the homepage.

Some ideas:
- Do we hide BRC-20, or all text/JSON inscriptions that are valid JSON? A good way to go might be to hide any text inscription which, when trimmed, starts with `{` and ends with `}`.
- Should we hide `.bitmap` and `.sats` names? Other names?

### PR DESCRIPTION
**Pull request by casey**
Fixes #2659.

### CODE REVIEW

**Review by raphjaph — APPROVED** [review]

**Comment by ordinalOS** [comment]
The number of .bitmap inscriptions post blockout is minimal, presenting no major concerns. Introducing bias into the ord client is a slippery slope. If brc-20 dominate the front-page so be it.

"The spirit of the people is greater than the Man’s technology"
-Huey P. Newton

**Comment by casey** [comment]
I don't think it's a slippery slope. All the inscriptions which are hidden from the homepage are really objectively not interesting to look at. BRC-20, bitmap, and gib inscriptions are protocol messages, and the overwhelming majority of users don't care about them, and will benefit from seeing a more interesting stream of inscriptions. The old homepage is still available under `/blocks` as well, so if people are interested in an unfiltered view, they can go there.

**Comment by ordinalOS** [comment]
I acknowledge the rationale behind pruning BRC-20 inscriptions, yet, from an objective standpoint, the unfiltered view of what's being inscribed offers a more intriguing insight for me personally. Deciding what is shown should be left to third party apps and marketplaces. Anecdotally, I was introduced to ordinals as a new way to grift PFP projects, I did not become interested until metaprotocols like .bitmap which is a highly efficient use of blockspace, more in-line with the ethos of bitcoin and satoshi who inscribed text to the genesis block, not jpegs. Filtering by content type could be one approach, but hand selecting winners and losers is creating a president for a ban list which will continue to grow, or will go into 1.0 with a hard coded bias being shown against .bitmap and gib selectively which represent less than 1% of daily inscriptions

**Comment by cbspears** [comment]
I strongly support explorers choosing to display inscriptions differently according to their design goals. This is in line with my view that we have several layers:

the protocol
implementations of the protocol
explorers

Just like Ordinals is a "lens" you view Bitcoin through, explorers are a "lens" you view Ordinals through. I think it not only makes sense for ordinals.com to filter inscriptions as it sees fit, I think it sets a good example for the ecosystem & other explorers.

**Comment by ordinalOS** [comment]
> I strongly support explorers choosing to display inscriptions differently according to their design goals. This is in line with my view that we have several layers:
> 
> the protocol implementations of the protocol explorers
> 
> Just like Ordinals is a "lens" you view Bitcoin through, explorers are a "lens" you view Ordinals through. I think it not only makes sense for ordinals.com to filter inscriptions as it sees fit, I think it sets a good example for the ecosystem & other explorers.

I agree to an extent, but de-ranking .bitmap seems more like a KEK and i don't think that sets a good example at all considering there are around 150 blocks per day, i'd personally rather see a .bitmap inscription on the front-page than someones half bakes pfp project. Also new users will be unaware of this code change as it will not be denoted on the front page in any way, creating a colored view of ordinals.

**Comment by Blockamoto** [comment]
I was under the impression the design goals of ordinals.com was to serve as ground truth for ordinals. Is this no longer the case?

Rather than pruning, why not add filters in the front-end?

I purposefully designed bitmap to NOT use JSON files, and instead use simple text, largely because I thought JSON looked ugly on ordinals.com. This was my concern from the beginning. I think the bitmaps are beautiful in their raw form, personally.

It has no bearing on the success of Bitmap of course, but it does display a clear bias towards certain kinds of inscriptions.

**Comment by raphjaph** [comment]
There's no pruning, literally just a filter on one page of ordinals.com. You can still see all bitmaps and brc-20 if you go to the blocks page or inscriptions page

**Comment by casey** [comment]
Also, there are way more than 144 `.bitmap` inscriptions per day, since there are often multiple attempts to claim a `.bitmap`. In in times of high fee pressure, like now, not many inscriptions are being made, so `.bitmap` inscriptions often make up a significant portion of the last 100 inscriptions, once BRC-20's are filtered.

**Comment by ordinalOS** [comment]
> There's no pruning, literally just a filter on one page of ordinals.com. You can still see all bitmaps and brc-20 if you go to the blocks page or inscriptions page

@Blockamoto my pruning i meant trimming (front front-page). 

Still there's no real argument here other than "we don't like seeing bitmap" there's a million other protocols, tap, orc-20, brc420, brc100. It's not the job or ordinals.com to act as a marketplace or to beautify the front page. it's a blockchain explorer

**Comment by casey** [comment]
> Still there's no real argument here other than "we don't like seeing bitmap"

"It makes the homepage ugly." is a valid argument. People go to to the homepage of ordinals.com, and their own `ord` instances, to see interesting looking inscriptions, not to see how many BRC-20 tokens have been minted, or how many duplicate or stale bitmap inscriptions were submitted to claim a block.

> there's a million other protocols, tap, orc-20, brc420, brc100. What will the next bitmap be? will you have to then keep pushing filters?

Whenever a protocol gets popular enough to make the homepage ugly, we will add a filter. Filters are one-line changes.

> It's not the job or ordinals.com to act as a marketplace or to beautify the front page.

It is not the job or ordinals.com to act as a marketplace, but it is the job of ordinasl.com to beautify the front page.

> it's a blockchain explorer, of sorts, Intertwined within the client (for better or for worse) and as block mentioned: The expected source of truth for ordinals protocol. If I want to see pretty stuff i can visit a number of other explorers and front-ends where biases are expected.

You can also visit the `/blocks` page, to see the latest, unfiltered inscriptions. There is not particular reason to display the latest unfiltered inscriptions on the home page, because the majority of users would prefer to see the latest interesting inscriptions, instead of the latest unfiltered inscriptions.

> As a users, i specifically visit ordinals.com to see unfiltered information, I want to see which brc-20 are being minted and traded, it gives me insight. And although it may be available to see on the blocks page, it will be misleading if not explicitly stated that the front-page is filtered.

The homepage doesn't say "these are the latest unfiltered inscriptions", it just presents 100 inscriptions. I don't think it's particularly misleading.

**Comment by cbspears** [comment]
> Still there's no real argument here other than "we don't like seeing bitmap" there's a million other protocols, tap, orc-20, brc420, brc100. It's not the job or ordinals.com to act as a marketplace or to beautify the front page. it's a blockchain explorer

I believe this is a common view because users have trouble differentiating between what is protocol, implementation of the protocol, and explorers of inscriptions using the reference implementation of the protocol. It's also my personal opinion that the developers of the reference implementation have not done a good job communicating the difference between the protocol and reference implementation, in fact often conflating the two. I think this is one reason why the adjustments to the landing page of the ordinals.com is controversial, because these different elements have not been sufficiently distinguished.

That said, I think demonstrating that Explorers should customize how they "interpret" Inscriptions is both a good design decision & leadership for the ecosystem. In the same way that ordinals.com may want to filter certain text & JSON from the landing page, other explorers may want to _only_ show those. I would argue some tools like GeniiData are actually also explorers, just selecting to focus on JSON/metaprotocols.

I think there should be consensus on protocol, expected similarities but _not necessarily_ consensus on implementation, and wide diversity among explorers.

**Comment by ordinalOS** [comment]
My only point is playing whack-a-mole is futile and selectively bias. Once development is finalized on ordinals, which i believe is the goal - you will have this short-list of things you tried to disappear and it's not going to age well. Filtering by content type, having toggles, or some other solution like showing the largest file sizes could be more fun and future proof. Personally I don't care about peoples pixel punks, so who's to say what's valid. @cbspears to your point about leadership, as someone involved with .bitmap community, we already have to deal with sanctimonious attitudes, having that co-signed even in this small way is not ideals. Very reminiscent of bitcoin maxis saying ordinals are a waist of space

**Comment by casey** [comment]
> My only point is playing whack-a-mole is futile and selectively bias.

It's not futile. Filters are one-line changes. The filter for BRC-20 also catches all JSON protocol inscriptions.

> Once development is finalized on ordinals, which i believe is the goal - you will have this short-list of things you tried to disappear and it's not going to age well.

Most users support this change. It's going to age fine.

> Filtering by content type, having toggles, or some other solution like showing the largest file sizes could be more fun and future proof.

We have a toggle. It's called clicking the "Blocks" tab.

> Personally I don't care about peoples pixel punks, so who's to say what's valid. @cbspears to your point about leadership, as someone involved with .bitmap community, we already have to deal with sanctimonious attitudes, having that co-signed even in this small way is not ideals. Very reminiscent of bitcoin maxis saying ordinals are a waist of space

We aren't saying that `.bitmap` or BRC-20 tokens are a waste of space. We're saying that they are visually uninteresting for the vast majority of users.

**Comment by cbspears** [comment]
> @cbspears to your point about leadership, as someone involved with .bitmap community, we already have to deal with sanctimonious attitudes, having that co-signed even in this small way is not ideals. Very reminiscent of bitcoin maxis saying ordinals are a waist of space

I want to keep this as much focused on the specific topic of what to display on the ordinals.com explorer, but to your point on sanctimonious attitudes, condescension I may communicate about .bitmap --

I've been very critical of Inscriptions as a mechanism for namespace in general as I believe these metaprotocols are structurally flawed long term. That doesn't mean that I'm against namespaces in general, in fact I think that's one of the most underexplored developments on Bitcoin. It also doesn't mean namespace & fungible token protocols won't have significant value accrual in the short term either.

I strongly believe that valid transactions, however dumb I may consider them, are important buyers of Bitcoin blockspace and I strongly believe we should allow price discovery of these assets, however stupid I may think they are. It's like the quote from Evelyn Beatrice Hall on Free Speech "I disapprove of what you say, but I will defend to the death your right to say it." just instead about using Bitcoin. That is a far cry from anti-Ordinals crowd many of whom wish to censor or prevent ordinals-related transactions at the protocol level.

That doesn't preclude filtering certain types of Inscriptions from the frontend of an explorer. I will probably even buy some bitmaps just to enjoy the ridiculousness of it all. Unfortunately most internet discourse is reductive & binary so I don't go into nuanced detail in a forum format as we have here.

I think that most bitmap enjoyers are probably just not aware of the technical shortcomings to the protocol and confuse technical criticism with personal & interpret price increase as invalidation of the technical criticisms.

**Comment by Blockamoto** [comment]
You shield yourself nicely from actually having to explain yourself regarding "technical limitations" by claiming it has nothing to do with your opinion that ordinals.com homepage should filter out metaprotocols from the homepages raw feed.

If you actually want to challenge the protocols technical standing, I'm happy to have this discussion wherever whenever. It could be that the shortcoming is not with the thousands of people who have come to a different conclusion.

I think beauty is in the eye of the beholder, and it's okay that you think bitmap is ugly. When I created it, to me it was the most beautiful thing I'd ever seen, but we can beg to differ.

**Comment by ordinalOS** [comment]
Ok well I stated my case and I support good work you guys are doing @casey 

> > @cbspears to your point about leadership, as someone involved with .bitmap community, we already have to deal with sanctimonious attitudes, having that co-signed even in this small way is not ideals. Very reminiscent of bitcoin maxis saying ordinals are a waist of space
> 
> I want to keep this focused on the specific topic of what to display on the ordinals.com explorer, but to your point on sanctimonious attitudes, condescension I may communicate about .bitmap --
> 
> I've been very critical of Inscriptions as a mechanism for namespace in general as I believe these metaprotocols are structurally flawed long term. That doesn't mean that I'm against namespaces in general, in fact I think that's one of the most underexplored developments on Bitcoin. It also doesn't mean namespace & fungible token protocols won't have significant value accrual in the short term either.
> 
> I strongly believe that valid transactions, however dumb I may consider them, are important buyers of Bitcoin blockspace and I strongly believe we should allow price discovery of these assets, however stupid I may think they are. It's like the quote from Evelyn Beatrice Hall on Free Speech "I disapprove of what you say, but I will defend to the death your right to say it." just instead about using Bitcoin. That is a far cry from anti-Ordinals crowd many of whom wish to censor or prevent ordinals-related transactions at the protocol level.
> 
> That doesn't preclude filtering certain types of Inscriptions from the frontend of an explorer. I will probably even buy some bitmaps just to enjoy the ridiculousness of it all. Unfortunately most internet discourse is reductive & binary so I often don't go into nuanced detail in a forum format as I can here.
> 

@cbspears I'd love to debate about this, but for sake of casey and raph time, I will rest my case and say that I support all the great work being done to ordinals, even if i disagree here. I personally rely on ordinals.com for unfiltered information and from a UIX perspective it's really confusing that /blocks/ will server different information than the front page which is presented as an explorer, not a curation. 

The .bitmap namespace has no technical shortcomings. It is just a text inscription. As i said before Satoshi himself added text to the genesis block. Ordfluencers jumping over from ETH and Solana, dismissed it due to bag biases and confusion why liquidity was flowing into a simple text file and not their PFP projects. By using Bitcoin as a verification layer, we can query block data off-chain to visualy represent .bitmap in any way, making it a highly versatile and compact use of block space. I have a very long history developing in crypto space and developing on EVM, have won multiple hackathons etc. To me bitmap is one of the most interesting ordinals projects with 800k supply, 30k holders, numerous decentralized developers. That is not found anywhere else. The sat hoarders and gatekeepers will argue that "uncommon sat" ownership gives you the block, which is great, but convince 30k people of it and then implement it. The social consensus supports .bitmap, aligning with Bitcoin's intended purpose as a verification tool.

**Comment by switch-900** [comment]
https://ordinals.com/inscription/5

**Pull request merged**
