### PR TITLE
Respect locked utxos

### PR DESCRIPTION
**Pull request by dannydeezy**
Locked utxos should not be available to spend. (https://github.com/ordinals/ord/issues/2496)

This PR attempts to ensure that if a utxo has been locked with the lockunspent bitcoin RPC call, then it will not be selected as a cardinal utxo. This enables people to safely lock utxos that they don't want ord to spend when doing inscriptions or sends (unless they are deliberately inscribing/sending that particular utxo)

### CODE REVIEW

**Comment by dannydeezy** [comment]
@raphjaph new version of (https://github.com/ordinals/ord/pull/2520) here

**Comment by raphjaph** [comment]
@dannydeezy we did a huge refactor of the inscribe logic, there's a bunch of conflicts now in the branch. If you could resolve them I can review. The new batch code is helpful to look at though, could be interesting for your service :)

**Comment by rot13maxi** [comment]
hey @dannydeezy I lifted your changes from here and did a tiny refactor on top of the batch interface here: #2618. Happy to PR against your branch if you want, or we can roll any changes you have into that PR. Either works for me.

**Comment by raphjaph** [comment]
Closing this since all the work is happening in #2618

**Comment by dannydeezy** [comment]
> hey @dannydeezy I lifted your changes from here and did a tiny refactor on top of the batch interface here: #2618. Happy to PR against your branch if you want, or we can roll any changes you have into that PR. Either works for me.

awesome thanks @rot13maxi

**Pull request closed without merging**
