### PR TITLE
Show total child count

### PR DESCRIPTION
**Pull request by arik-so**
Add a child totalizer to the inscription page.

### CODE REVIEW

**Comment by casey** [comment]
We're discussing how to display the number of children on the /inscription page, and not coming to an obvious conclusion. Do you want this PR so that the number of children is displayed, or so that the number of children is returned from the API? If you don't care that the number of children is displayed on the /inscription page, we could remove that from this PR and worry about it later.

**Comment by casey** [comment]
Gotcha. We don't really like modifying the "children" `<dt>` So maybe it could go in the `all` link instead? I.e. `all 4` or `all 4 children`.

**Comment by raphjaph** [comment]
> Come to think of it though, it might be prudent for the /children page to also show the total somewhere.

That makes sense. Let's put it in a separate PR though

**Review by raphjaph — APPROVED** [review]
LGTM

**Pull request merged**
