### PR TITLE
feat(redb): add repair progress

### PR DESCRIPTION
**Pull request by nikicat**
This PR adds progress bar for database repair. It doesn't work smoothly though: due to redb limitation, only 30%, 60% and 90% steps exist.

### CODE REVIEW

**Comment by casey** [comment]
Does this need to be in a background thread? Can we update the progress bar directly in the callback?

**Comment by nikicat** [comment]
> Does this need to be in a background thread? Can we update the progress bar directly in the callback?

We can't because progress callback should be an `Fn`, not `FnMut`

**Comment by casey** [comment]
In that case, try wrapping the progress bar in a Mutex.

**Comment by casey** [comment]
Nice, merged!

**Pull request merged**
