### PR TITLE
Mint runes with wallet

### PR DESCRIPTION
**Pull request by raphjaph**
todo:
- [x] check deadline against block time
- [x] test that mint does not select inscribed UTXOs
- [x] add mintable function which is used both by RuneUpdater and `ord wallet mint`

### CODE REVIEW

**Comment by cliobitcoinbank** [comment]
LETS FUCKING GO!!!

**Comment by BitSavage0202** [comment]
Release the spirits... It begins

**Review by casey — APPROVED** [review]
LGTM!

**Comment by PGone-8547** [comment]
Go!!!

**Comment by traithon9x** [comment]
do it

**Pull request merged**
