### PR TITLE
Only load necessary language highlight module

### PR DESCRIPTION
**Pull request by casey**
This avoids loading highlight modules which we aren't going to use.

### CODE REVIEW

**Comment by elocremarc** [comment]
Cool! While were in here can we add x-javascript as a inscription type and code syntax?
See inscription https://ordinals.com/inscription/c5942064bea79672efc5d8331d84171ad2ebb086873e4eb24f7184b159702b87i0

**Comment by casey** [comment]
@elocremarc I'm not opposed. I added it to this PR.

**Review by raphjaph — APPROVED** [review]
LGTM!

**Comment by elocremarc** [comment]
Closes https://github.com/ordinals/ord/issues/2615

**Pull request merged**
