### PR TITLE
Update rust-bitcoin in ord

### LINKED ISSUE #3982: ```ord``` fails with Bitcoin Core v28.0
```
[INFO  ord::index] Failed to connect to Bitcoin Core RPC at `127.0.0.1:8332/`:  JSON error: invalid type: sequence, expected a string
[WARN  ord::subcommand::server] Updating index: Failed to connect to Bitcoin Core RPC at `127.0.0.1:8332/`:  JSON error: invalid type: sequence, expected a string
```

image

### PR DESCRIPTION
**Pull request by raphjaph**
This will take forever.

Fixes #3982

### CODE REVIEW

**Comment by cryptoquick** [comment]
Thank you for starting this work. Let me know if you would like some help. I keep running into this:

```
mismatched types
`bdk_wallet::bitcoin::Transaction` and `Transaction` have similar names, but are actually distinct types
perhaps two different versions of crate `bitcoin` are being used?rustc[Click for full compiler diagnostic](rust-analyzer-diagnostics-view:/diagnostic%20message%20%5B5%5D?5#file%3A%2F%2F%2Fhome%2Fhunter%2FProjects%2Fducat%2Fguardian%2Fcrates%2Fvault_actions%2Fsrc%2Frepay.rs)
repay.rs(299, 24): arguments to this function are incorrect
transaction.rs(671, 1): `bdk_wallet::bitcoin::Transaction` is defined in crate `bitcoin`
transaction.rs(706, 1): `Transaction` is defined in crate `bitcoin`
runestone.rs(25, 10): associated function defined here
```

**Comment by raphjaph** [comment]
> Thank you for starting this work. Let me know if you would like some help. I keep running into this:
> 
> ```
> mismatched types
> `bdk_wallet::bitcoin::Transaction` and `Transaction` have similar names, but are actually distinct types
> perhaps two different versions of crate `bitcoin` are being used?rustc[Click for full compiler diagnostic](rust-analyzer-diagnostics-view:/diagnostic%20message%20%5B5%5D?5#file%3A%2F%2F%2Fhome%2Fhunter%2FProjects%2Fducat%2Fguardian%2Fcrates%2Fvault_actions%2Fsrc%2Frepay.rs)
> repay.rs(299, 24): arguments to this function are incorrect
> transaction.rs(671, 1): `bdk_wallet::bitcoin::Transaction` is defined in crate `bitcoin`
> transaction.rs(706, 1): `Transaction` is defined in crate `bitcoin`
> runestone.rs(25, 10): associated function defined here
> ```

Yeah, the `rust-bitcoin` library constantly moves types around between modules so the Rust type system thinks they are different. This also means dependant crates we use like `miniscript` and `bitcoincore-rpc` have to be upgraded in tandem. It's an extremely manual job. Currently I've found around 700 places in our code base where I have to change something.

**Comment by cryptoquick** [comment]
I know. And that's just to 0.31.2. But thank you for taking this on. It'll help with bits of code like this:
`script_pubkey: ScriptBuf::from_bytes(runestone.encipher().to_bytes())`
That were originally just:
`script_pubkey: runestone.encipher()`
This might have a slight performance impact if used often enough, such as for verification, and we also get some loss of type safety.
In the grand scheme of things this is low priority, but it's still technical debt.

**Comment by cryptoquick** [comment]
Great work, guys!

**Comment by raphjaph** [comment]
Soon, just gonna check what else we can merge. Probably by next week

**Comment by cryptoquick** [comment]
that soom!

**Pull request merged**
