### PR TITLE
fix: preview csp value

### LINKED ISSUE #3253: Preview broken on Safari on localhost
I was running ord server locally, and inscription previews were broken on safari.

I'm not sure what the issue is, and passing `--csp-origin http://localhost` didn't seem to fix it.

### PR DESCRIPTION
**Pull request by bingryan**
## Description

add preview csp value

## Related Issue

Fixes #3253

## Usage

`--csp-origin http://localhost` can fix safari `Content Security Policy` for ord server locally

### CODE REVIEW

**Comment by bingryan** [comment]
BTW, i add `script-src-elem 'self' https://cdn.jsdelivr.net` for default `CONTENT_SECURITY_POLICY` for some media, Please pay attention to this when code review. 
@casey @raphjaph

**Comment by bingryan** [comment]
@raphjaph code review plz :)

**Comment by raphjaph** [comment]
Did you test if it works on Safari now?

**Comment by bingryan** [comment]
image
Check again, it's working for add  `--csp-origin http://localhost`

- [x] chrome
- [x] Firefox
- [x] Safari
- [x] Edge
- [x] Arc

**Review by raphjaph — APPROVED** [review]
LGTM!

**Comment by casey** [comment]
@bingryan Thanks for the PR! I refactored it to hopefully make it a bit clearer. The big change was that instead of appending the CSP origin, if present, I replaced `'self'` with the CSP origin.

**Comment by bingryan** [comment]
> @bingryan Thanks for the PR! I refactored it to hopefully make it a bit clearer. The big change was that instead of appending the CSP origin, if present, I replaced `'self'` with the CSP origin.

thanks，casey.

**Pull request merged**
