### PR TITLE
Fixed using sat or satpoint with batch inscribe

### PR DESCRIPTION
**Pull request by pokrovskyy**
It seems there is a typo checking for `sat`/`satpoint` with `same-sat` mode during batch inscribe.

### CODE REVIEW

**Comment by pokrovskyy** [comment]
Hmm @raphjaph not sure about this limitation though. Why `satpoint` is only available in `same-sat` mode? Eg. I want to use `separate-outputs` and use a specific satpoint  - I may have various eligible cardinals in my wallet, but want to use a specific one for that particular batch

**Comment by raphjaph** [comment]
`satpoint` can be set in two places. Once at the root level when you want to inscribe one or more inscriptions on a specific `sat` (if you have the sat index) or on a `satpoint` (when you don't have a sat index but now the exact location of the sat). The root level `satpoint` requires you to use `same-sat` mode so it's clear that all inscriptions land on the root level specified `satpoint`. 

The other place you can set the `satpoint` is inside the inscription entry. This means the inscription will be inscribed on that `satpoint`. For this you need to set the `satpoints` mode. This allows specifying different satpoints for each inscription and also means each inscription will be in its own output. 

[This transaction](https://ordinals.com/tx/fd63e010579d69af0b06b727c8b296518eda002a4133397dd1fa95a696d09284) was produced by the `batch.yaml` below:
```
mode: satpoints
parents:
  - d30a35910fdb73c1eb97b6b06fe70c8c0dd40b621e7fe6f1bbeab9ac4616356fi1
inscriptions:
  - file: ephemera/collection/cycle_08/IAEK-0128/IAEK-0128.html
    satpoint: e49ac4c2cde290659e6e1de422ca8ee112869b9f3213366418c8c26477a2a5be:0:0
    destination: bc1pdpljvkq0pwchkgjeh2m9q5nhstpe4pelq8hz8k4gustrajl2482sxt2f6s
    metadata:
      Call Sign: NEUTRALMEMORY
      Serial Number: IAEK-0128
      Housing: IAEK-EK01-RRK-W
      Sundial: IAEK-EK02
      Orbit Controller: IAEK-OC02-BC-L
      CAL Code: 2009-0401-1611
      Operating System: 0.0.6
      Ephemerides:
        Sun:
          Zodiac Sign: Aries
          Zodiac Degree: 11.939047
          Right Ascension: 0.191627
          Declination: 0.082358
          RA (Degrees): 00 43 55.06
          Dec (Degrees): +04 43 07.5
          Apparent Magnitude: -26.743
        Moon:
          Zodiac Sign: Gemini
          Zodiac Degree: 29.860516
          Right Ascension: 1.568089
          Declination: 0.455093
          RA (Degrees): 05 59 22.77
          Dec (Degrees): +26 04 29.6
          Apparent Magnitude: -9.757
        Mercury:
          Zodiac Sign: Aries
          Zodiac Degree: 13.553099
          Right Ascension: 0.223674
          Declination: 0.079135
          RA (Degrees): 00 51 15.74
          Dec (Degrees): +04 32 02.8
          Apparent Magnitude: -2.058
        Venus:
          Zodiac Sign: Aries
          Zodiac Degree: 4.149051
          Right Ascension: 0.013595
          Declination: 0.149863
          RA (Degrees): 00 03 06.94
          Dec (Degrees): +08 35 11.4
          Apparent Magnitude: -4.1
        Mars:
          Zodiac Sign: Pisces
          Zodiac Degree: 13.598096
          Right Ascension: 6.027337
          Declination: -0.131439
          RA (Degrees): 23 01 21.83
          Dec (Degrees): '-07 31 51.3'
          Apparent Magnitude: 1.192
        Jupiter:
          Zodiac Sign: Aquarius
          Zodiac Degree: 19.097925
          Right Ascension: 5.614904
          Declination: -0.27314
          RA (Degrees): 21 26 50.47
          Dec (Degrees): '-15 38 59.2'
          Apparent Magnitude: -2.067
        Saturn:
          Zodiac Sign: Virgo
          Zodiac Degree: 16.438749
          Right Ascension: 2.939305
          Declination: 0.129889
          RA (Degrees): 11 13 38.35
          Dec (Degrees): +07 26 31.6
          Apparent Magnitude: 0.577
        Uranus:
          Zodiac Sign: Pisces
          Zodiac Degree: 23.586284
          Right Ascension: 6.185456
          Declination: -0.056132
          RA (Degrees): 23 37 36.12
          Dec (Degrees): '-03 12 58.0'
          Apparent Magnitude: 6.017
        Neptune:
          Zodiac Sign: Aquarius
          Zodiac Degree: 25.482801
          Right Ascension: 5.722532
          Declination: -0.233428
          RA (Degrees): 21 51 30.46
          Dec (Degrees): '-13 22 27.9'
          Apparent Magnitude: 7.824
        Pluto:
          Zodiac Sign: Capricorn
          Zodiac Degree: 3.164386
          Right Ascension: 4.77006
          Declination: -0.308167
          RA (Degrees): 18 13 13.03
          Dec (Degrees): '-17 39 24.1'
          Apparent Magnitude: 14.062
  - file: ephemera/collection/cycle_08/IAEK-0129/IAEK-0129.html
    satpoint: e49ac4c2cde290659e6e1de422ca8ee112869b9f3213366418c8c26477a2a5be:1:0
    destination: bc1pw8zghwtxxpysmj3hz8sml8k02xy55zrcvueav8prus8uwl26446shehf72
    metadata:
      Call Sign: BUBBLEEXAMPLE
      Serial Number: IAEK-0129
      Housing: IAEK-EK01-FFK-G
      Sundial: IAEK-EK02
      Orbit Controller: IAEK-OC06-WB
      CAL Code: 2022-1225-0756
      Operating System: 0.0.6
      Ephemerides:
        Sun:
          Zodiac Sign: Capricorn
          Zodiac Degree: 3.175995
          Right Ascension: 4.772794
          Declination: -0.408415
          RA (Degrees): 18 13 50.63
          Dec (Degrees): '-23 24 01.6'
          Apparent Magnitude: -26.778
        Moon:
          Zodiac Sign: Aquarius
          Zodiac Degree: 0.592064
          Right Ascension: 5.309083
          Declination: -0.448679
          RA (Degrees): 20 16 45.13
          Dec (Degrees): '-25 42 26.6'
          Apparent Magnitude: -6.813
        Mercury:
          Zodiac Sign: Capricorn
          Zodiac Degree: 22.646282
          Right Ascension: 5.142171
          Declination: -0.392506
          RA (Degrees): 19 38 29.93
          Dec (Degrees): '-22 29 20.1'
          Apparent Magnitude: -0.251
        Venus:
          Zodiac Sign: Capricorn
          Zodiac Degree: 18.712574
          Right Ascension: 5.069249
          Declination: -0.407358
          RA (Degrees): 19 21 47.18
          Dec (Degrees): '-23 20 23.6'
          Apparent Magnitude: -3.898
        Mars:
          Zodiac Sign: Gemini
          Zodiac Degree: 10.105454
          Right Ascension: 1.187433
          Declination: 0.430571
          RA (Degrees): 04 32 08.37
          Dec (Degrees): +24 40 11.6
          Apparent Magnitude: -1.524
        Jupiter:
          Zodiac Sign: Aries
          Zodiac Degree: 0.1317
          Right Ascension: 0.011243
          Declination: -0.02015
          RA (Degrees): 00 02 34.60
          Dec (Degrees): '-01 09 16.3'
          Apparent Magnitude: -2.392
        Saturn:
          Zodiac Sign: Aquarius
          Zodiac Degree: 21.460204
          Right Ascension: 5.659298
          Declination: -0.271006
          RA (Degrees): 21 37 00.93
          Dec (Degrees): '-15 31 39.1'
          Apparent Magnitude: 0.85
        Uranus:
          Zodiac Sign: Taurus
          Zodiac Degree: 14.965985
          Right Ascension: 0.743726
          Declination: 0.278905
          RA (Degrees): 02 50 26.96
          Dec (Degrees): +15 58 48.3
          Apparent Magnitude: 5.704
        Neptune:
          Zodiac Sign: Pisces
          Zodiac Degree: 22.459492
          Right Ascension: 6.170551
          Declination: -0.071305
          RA (Degrees): 23 34 11.17
          Dec (Degrees): '-04 05 07.7'
          Apparent Magnitude: 7.771
        Pluto:
          Zodiac Sign: Capricorn
          Zodiac Degree: 27.137961
          Right Ascension: 5.230101
          Declination: -0.400216
          RA (Degrees): 19 58 39.05
          Dec (Degrees): '-22 55 50.4'
          Apparent Magnitude: 14.482
  - file: ephemera/collection/cycle_08/IAEK-0130/IAEK-0130.html
    satpoint: e49ac4c2cde290659e6e1de422ca8ee112869b9f3213366418c8c26477a2a5be:2:0
    destination: bc1p3fa7mx4f3s9yyj6fcvcurw0qlk5h4nay0f9senqetcczfzpqjr2qq7znz0
    metadata:
      Call Sign: VICIOUSSTEREO
      Serial Number: IAEK-0130
      Housing: IAEK-EK01-B-I
      Sundial: IAEK-EK02
      Orbit Controller: IAEK-OC03-BL
      CAL Code: 2009-0123-1827
      Operating System: 0.0.6
      Ephemerides:
        Sun:
          Zodiac Sign: Aquarius
          Zodiac Degree: 3.765357
          Right Ascension: 5.342119
          Declination: -0.337036
          RA (Degrees): 20 24 19.41
          Dec (Degrees): '-19 18 38.6'
          Apparent Magnitude: -26.776
        Moon:
          Zodiac Sign: Capricorn
          Zodiac Degree: 5.366096
          Right Ascension: 4.817082
          Declination: -0.466041
          RA (Degrees): 18 23 59.63
          Dec (Degrees): '-26 42 07.9'
          Apparent Magnitude: -6.586
        Mercury:
          Zodiac Sign: Capricorn
          Zodiac Degree: 26.716144
          Right Ascension: 5.201796
          Declination: -0.302778
          RA (Degrees): 19 52 09.83
          Dec (Degrees): '-17 20 52.5'
          Apparent Magnitude: 3.456
        Venus:
          Zodiac Sign: Pisces
          Zodiac Degree: 20.594803
          Right Ascension: 6.128489
          Declination: -0.055998
          RA (Degrees): 23 24 32.77
          Dec (Degrees): '-03 12 30.5'
          Apparent Magnitude: -4.61
        Mars:
          Zodiac Sign: Capricorn
          Zodiac Degree: 20.707058
          Right Ascension: 5.105733
          Declination: -0.396471
          RA (Degrees): 19 30 08.87
          Dec (Degrees): '-22 42 58.0'
          Apparent Magnitude: 1.267
        Jupiter:
          Zodiac Sign: Aquarius
          Zodiac Degree: 4.134145
          Right Ascension: 5.350668
          Declination: -0.342962
          RA (Degrees): 20 26 16.97
          Dec (Degrees): '-19 39 00.9'
          Apparent Magnitude: -1.931
        Saturn:
          Zodiac Sign: Virgo
          Zodiac Degree: 21.157521
          Right Ascension: 3.014652
          Declination: 0.095646
          RA (Degrees): 11 30 54.44
          Dec (Degrees): +05 28 48.5
          Apparent Magnitude: 0.694
        Uranus:
          Zodiac Sign: Pisces
          Zodiac Degree: 19.937772
          Right Ascension: 6.126884
          Declination: -0.081431
          RA (Degrees): 23 24 10.70
          Dec (Degrees): '-04 39 56.4'
          Apparent Magnitude: 5.99
        Neptune:
          Zodiac Sign: Aquarius
          Zodiac Degree: 23.071846
          Right Ascension: 5.681583
          Declination: -0.247172
          RA (Degrees): 21 42 07.38
          Dec (Degrees): '-14 09 42.8'
          Apparent Magnitude: 7.842
        Pluto:
          Zodiac Sign: Capricorn
          Zodiac Degree: 1.91795
          Right Ascension: 4.747364
          Declination: -0.309724
          RA (Degrees): 18 08 00.94
          Dec (Degrees): '-17 44 45.1'
          Apparent Magnitude: 14.091
  - file: ephemera/collection/cycle_08/IAEK-0131/IAEK-0131.html
    satpoint: e49ac4c2cde290659e6e1de422ca8ee112869b9f3213366418c8c26477a2a5be:3:0
    destination: bc1peszxwt4yx7mty20a2dypz3wxt2qfm4m9mzt2cej7r8kyp6327xmshcpl4f
    metadata:
      Call Sign: CRUCIALSTRATEGY
      Serial Number: IAEK-0131
      Housing: IAEK-EK01-BBK-W
      Sundial: IAEK-EK02
      Orbit Controller: IAEK-OC06-RW
      CAL Code: 2017-0210-1048
      Operating System: 0.0.6
      Ephemerides:
        Sun:
          Zodiac Sign: Aquarius
          Zodiac Degree: 21.657298
          Right Ascension: 5.655429
          Declination: -0.249362
          RA (Degrees): 21 36 07.73
          Dec (Degrees): '-14 17 14.6'
          Apparent Magnitude: -26.771
        Moon:
          Zodiac Sign: Leo
          Zodiac Degree: 14.46934
          Right Ascension: 2.37647
          Declination: 0.244667
          RA (Degrees): 09 04 38.81
          Dec (Degrees): +14 01 06.1
          Apparent Magnitude: -12.584
        Mercury:
          Zodiac Sign: Aquarius
          Zodiac Degree: 4.351119
          Right Ascension: 5.359309
          Declination: -0.360125
          RA (Degrees): 20 28 15.79
          Dec (Degrees): '-20 38 01.1'
          Apparent Magnitude: -0.365
        Venus:
          Zodiac Sign: Aries
          Zodiac Degree: 4.729728
          Right Ascension: 0.053577
          Declination: 0.083985
          RA (Degrees): 00 12 16.74
          Dec (Degrees): +04 48 43.1
          Apparent Magnitude: -4.815
        Mars:
          Zodiac Sign: Aries
          Zodiac Degree: 9.59546
          Right Ascension: 0.155486
          Declination: 0.062603
          RA (Degrees): 00 35 38.09
          Dec (Degrees): +03 35 12.8
          Apparent Magnitude: 1.286
        Jupiter:
          Zodiac Sign: Libra
          Zodiac Degree: 22.872735
          Right Ascension: 3.520322
          Declination: -0.131797
          RA (Degrees): 13 26 47.90
          Dec (Degrees): '-07 33 05.0'
          Apparent Magnitude: -2.206
        Saturn:
          Zodiac Sign: Sagittarius
          Zodiac Degree: 25.192791
          Right Ascension: 4.621865
          Declination: -0.385023
          RA (Degrees): 17 39 15.21
          Dec (Degrees): '-22 03 36.7'
          Apparent Magnitude: 0.519
        Uranus:
          Zodiac Sign: Aries
          Zodiac Degree: 21.103901
          Right Ascension: 0.344159
          Declination: 0.134316
          RA (Degrees): 01 18 52.52
          Dec (Degrees): +07 41 44.6
          Apparent Magnitude: 5.909
        Neptune:
          Zodiac Sign: Pisces
          Zodiac Degree: 10.739839
          Right Ascension: 5.978618
          Declination: -0.145279
          RA (Degrees): 22 50 11.90
          Dec (Degrees): '-08 19 25.9'
          Apparent Magnitude: 7.831
        Pluto:
          Zodiac Sign: Capricorn
          Zodiac Degree: 18.046075
          Right Ascension: 5.051219
          Declination: -0.371266
          RA (Degrees): 19 17 39.25
          Dec (Degrees): '-21 16 19.2'
          Apparent Magnitude: 14.312
  - file: ephemera/collection/cycle_08/IAEK-0132/IAEK-0132.html
    satpoint: e49ac4c2cde290659e6e1de422ca8ee112869b9f3213366418c8c26477a2a5be:4:0
    destination: bc1p9uf47zq0uxgdnuljw3h3m857dxdkrkkk07rzpnvvaqgszhcrw3gslus4rp
    metadata:
      Call Sign: STABLEVIOLIN
      Serial Number: IAEK-0132
      Housing: IAEK-EK01-BBK-G
      Sundial: IAEK-EK02
      Orbit Controller: IAEK-OC01-E
      CAL Code: 2009-0218-1114
      Operating System: 0.0.6
      Ephemerides:
        Sun:
          Zodiac Sign: Aquarius
          Zodiac Degree: 29.809206
          Right Ascension: 5.792885
          Declination: -0.201425
          RA (Degrees): 22 07 37.88
          Dec (Degrees): '-11 32 26.8'
          Apparent Magnitude: -26.767
        Moon:
          Zodiac Sign: Sagittarius
          Zodiac Degree: 16.552749
          Right Ascension: 4.447671
          Declination: -0.483205
          RA (Degrees): 16 59 19.87
          Dec (Degrees): '-27 41 08.1'
          Apparent Magnitude: -9.35
        Mercury:
          Zodiac Sign: Aquarius
          Zodiac Degree: 4.12875
          Right Ascension: 5.35014
          Declination: -0.341319
          RA (Degrees): 20 26 09.71
          Dec (Degrees): '-19 33 22.2'
          Apparent Magnitude: 0.001
        Venus:
          Zodiac Sign: Aries
          Zodiac Degree: 10.573655
          Right Ascension: 0.140071
          Declination: 0.141706
          RA (Degrees): 00 32 06.12
          Dec (Degrees): +08 07 08.9
          Apparent Magnitude: -4.85
        Mars:
          Zodiac Sign: Aquarius
          Zodiac Degree: 10.590464
          Right Ascension: 5.46884
          Declination: -0.324433
          RA (Degrees): 20 53 21.95
          Dec (Degrees): '-18 35 19.1'
          Apparent Magnitude: 1.266
        Jupiter:
          Zodiac Sign: Aquarius
          Zodiac Degree: 10.161393
          Right Ascension: 5.458432
          Declination: -0.317
          RA (Degrees): 20 50 58.83
          Dec (Degrees): '-18 09 46.0'
          Apparent Magnitude: -1.954
        Saturn:
          Zodiac Sign: Virgo
          Zodiac Degree: 19.661971
          Right Ascension: 2.991155
          Declination: 0.107317
          RA (Degrees): 11 25 31.34
          Dec (Degrees): +06 08 55.7
          Apparent Magnitude: 0.562
        Uranus:
          Zodiac Sign: Pisces
          Zodiac Degree: 21.209427
          Right Ascension: 6.147283
          Declination: -0.07255
          RA (Degrees): 23 28 51.21
          Dec (Degrees): '-04 09 24.5'
          Apparent Magnitude: 6.015
        Neptune:
          Zodiac Sign: Aquarius
          Zodiac Degree: 24.036731
          Right Ascension: 5.697992
          Declination: -0.241683
          RA (Degrees): 21 45 53.01
          Dec (Degrees): '-13 50 50.6'
          Apparent Magnitude: 7.846
        Pluto:
          Zodiac Sign: Capricorn
          Zodiac Degree: 2.634186
          Right Ascension: 4.760418
          Declination: -0.309309
          RA (Degrees): 18 11 00.45
          Dec (Degrees): '-17 43 19.6'
          Apparent Magnitude: 14.094
  - file: ephemera/collection/cycle_08/IAEK-0133/IAEK-0133.html
    satpoint: e49ac4c2cde290659e6e1de422ca8ee112869b9f3213366418c8c26477a2a5be:5:0
    destination: bc1prjctkd6svw2ncllase350hp2ljqhjsr0v8uwaqfss9qaz0h0m6lsd47fhj
    metadata:
      Call Sign: NOBLEHISTORY
      Serial Number: IAEK-0133
      Housing: IAEK-EK01-FFK-W
      Sundial: IAEK-EK02
      Orbit Controller: IAEK-OC04-S
      CAL Code: 2021-1225-1510
      Operating System: 0.0.6
      Ephemerides:
        Sun:
          Zodiac Sign: Capricorn
          Zodiac Degree: 3.740102
          Right Ascension: 4.783518
          Declination: -0.408156
          RA (Degrees): 18 16 18.09
          Dec (Degrees): '-23 23 08.3'
          Apparent Magnitude: -26.778
        Moon:
          Zodiac Sign: Virgo
          Zodiac Degree: 16.051054
          Right Ascension: 2.946204
          Declination: 0.16327
          RA (Degrees): 11 15 13.21
          Dec (Degrees): +09 21 16.8
          Apparent Magnitude: -10.731
        Mercury:
          Zodiac Sign: Capricorn
          Zodiac Degree: 18.344034
          Right Ascension: 5.064837
          Declination: -0.424961
          RA (Degrees): 19 20 46.51
          Dec (Degrees): '-24 20 54.4'
          Apparent Magnitude: -0.776
        Venus:
          Zodiac Sign: Capricorn
          Zodiac Degree: 25.394751
          Right Ascension: 5.185671
          Declination: -0.34629
          RA (Degrees): 19 48 28.09
          Dec (Degrees): '-19 50 27.5'
          Apparent Magnitude: -4.614
        Mars:
          Zodiac Sign: Sagittarius
          Zodiac Degree: 8.287262
          Right Ascension: 4.302722
          Declination: -0.37958
          RA (Degrees): 16 26 06.67
          Dec (Degrees): '-21 44 53.9'
          Apparent Magnitude: 1.521
        Jupiter:
          Zodiac Sign: Aquarius
          Zodiac Degree: 29.034946
          Right Ascension: 5.786206
          Declination: -0.222541
          RA (Degrees): 22 06 06.04
          Dec (Degrees): '-12 45 02.4'
          Apparent Magnitude: -2.156
        Saturn:
          Zodiac Sign: Aquarius
          Zodiac Degree: 10.930175
          Right Ascension: 5.473704
          Declination: -0.318988
          RA (Degrees): 20 54 28.83
          Dec (Degrees): '-18 16 36.1'
          Apparent Magnitude: 0.764
        Uranus:
          Zodiac Sign: Taurus
          Zodiac Degree: 10.758236
          Right Ascension: 0.671403
          Declination: 0.255908
          RA (Degrees): 02 33 52.46
          Dec (Degrees): +14 39 44.8
          Apparent Magnitude: 5.726
        Neptune:
          Zodiac Sign: Pisces
          Zodiac Degree: 20.268591
          Right Ascension: 6.134949
          Declination: -0.085541
          RA (Degrees): 23 26 01.60
          Dec (Degrees): '-04 54 04.2'
          Apparent Magnitude: 7.775
        Pluto:
          Zodiac Sign: Capricorn
          Zodiac Degree: 25.435316
          Right Ascension: 5.196571
          Declination: -0.396904
          RA (Degrees): 19 50 57.98
          Dec (Degrees): '-22 44 27.3'
          Apparent Magnitude: 14.451
  - file: ephemera/collection/cycle_08/IAEK-0134/IAEK-0134.html
    satpoint: e49ac4c2cde290659e6e1de422ca8ee112869b9f3213366418c8c26477a2a5be:6:0
    destination: bc1pqgrylhqzy7ljzsfajp8rqkdrjlngcp6w8czy763d790tvk2gsdhqdq2juu
    metadata:
      Call Sign: EASYQUALITY
      Serial Number: IAEK-0134
      Housing: IAEK-EK01-WWS-W
      Sundial: IAEK-EK02
      Orbit Controller: IAEK-OC06-WB
      CAL Code: 2013-0703-1253
      Operating System: 0.0.6
      Ephemerides:
        Sun:
          Zodiac Sign: Cancer
          Zodiac Degree: 11.566791
          Right Ascension: 1.790272
          Declination: 0.400254
          RA (Degrees): 06 50 18.01
          Dec (Degrees): +22 55 58.3
          Apparent Magnitude: -26.706
        Moon:
          Zodiac Sign: Taurus
          Zodiac Degree: 18.954746
          Right Ascension: 0.815758
          Declination: 0.290591
          RA (Degrees): 03 06 57.48
          Dec (Degrees): +16 38 58.7
          Apparent Magnitude: -8.25
        Mercury:
          Zodiac Sign: Cancer
          Zodiac Degree: 21.16847
          Right Ascension: 1.959523
          Declination: 0.31522
          RA (Degrees): 07 29 05.37
          Dec (Degrees): +18 03 38.8
          Apparent Magnitude: 3.895
        Venus:
          Zodiac Sign: Leo
          Zodiac Degree: 6.880295
          Right Ascension: 2.263919
          Declination: 0.351383
          RA (Degrees): 08 38 51.12
          Dec (Degrees): +20 07 58.0
          Apparent Magnitude: -3.888
        Mars:
          Zodiac Sign: Gemini
          Zodiac Degree: 22.981845
          Right Ascension: 1.436998
          Declination: 0.413052
          RA (Degrees): 05 29 20.14
          Dec (Degrees): +23 39 58.0
          Apparent Magnitude: 1.498
        Jupiter:
          Zodiac Sign: Cancer
          Zodiac Degree: 1.517447
          Right Ascension: 1.599616
          Declination: 0.405304
          RA (Degrees): 06 06 36.30
          Dec (Degrees): +23 13 20.0
          Apparent Magnitude: -1.909
        Saturn:
          Zodiac Sign: Scorpio
          Zodiac Degree: 4.642071
          Right Ascension: 3.721482
          Declination: -0.187012
          RA (Degrees): 14 12 54.05
          Dec (Degrees): '-10 42 54.0'
          Apparent Magnitude: 0.491
        Uranus:
          Zodiac Sign: Aries
          Zodiac Degree: 12.248166
          Right Ascension: 0.201369
          Declination: 0.073264
          RA (Degrees): 00 46 09.02
          Dec (Degrees): +04 11 51.8
          Apparent Magnitude: 5.889
        Neptune:
          Zodiac Sign: Pisces
          Zodiac Degree: 4.998511
          Right Ascension: 5.883223
          Declination: -0.179753
          RA (Degrees): 22 28 20.13
          Dec (Degrees): '-10 17 56.7'
          Apparent Magnitude: 7.724
        Pluto:
          Zodiac Sign: Capricorn
          Zodiac Degree: 10.055323
          Right Ascension: 4.898789
          Declination: -0.346275
          RA (Degrees): 18 42 43.18
          Dec (Degrees): '-19 50 24.3'
          Apparent Magnitude: 14.05
  - file: ephemera/collection/cycle_08/IAEK-0135/IAEK-0135.html
    satpoint: e49ac4c2cde290659e6e1de422ca8ee112869b9f3213366418c8c26477a2a5be:7:0
    destination: bc1pz6sh480m7a43vs5nlwfvf7k0l85a49ctwnvauuxdcql4wrwhxqhqpap82c
    metadata:
      Call Sign: READYBALCONY
      Serial Number: IAEK-0135
      Housing: IAEK-EK01-FFK-W
      Sundial: IAEK-EK02
      Orbit Controller: IAEK-OC01-L
      CAL Code: 2009-1231-2138
      Operating System: 0.0.6
      Ephemerides:
        Sun:
          Zodiac Sign: Capricorn
          Zodiac Degree: 10.21121
          Right Ascension: 4.906254
          Declination: -0.402235
          RA (Degrees): 18 44 25.84
          Dec (Degrees): '-23 02 46.9'
          Apparent Magnitude: -26.779
        Moon:
          Zodiac Sign: Cancer
          Zodiac Degree: 12.053034
          Right Ascension: 1.80008
          Declination: 0.405897
          RA (Degrees): 06 52 32.87
          Dec (Degrees): +23 15 22.2
          Apparent Magnitude: -12.878
        Mercury:
          Zodiac Sign: Capricorn
          Zodiac Degree: 18.954953
          Right Ascension: 5.066414
          Declination: -0.35799
          RA (Degrees): 19 21 08.19
          Dec (Degrees): '-20 30 40.8'
          Apparent Magnitude: 2.655
        Venus:
          Zodiac Sign: Capricorn
          Zodiac Degree: 7.586913
          Right Ascension: 4.857028
          Declination: -0.412832
          RA (Degrees): 18 33 08.93
          Dec (Degrees): '-23 39 12.7'
          Apparent Magnitude: -3.912
        Mars:
          Zodiac Sign: Leo
          Zodiac Degree: 18.68641
          Right Ascension: 2.484354
          Declination: 0.327915
          RA (Degrees): 09 29 22.32
          Dec (Degrees): +18 47 17.3
          Apparent Magnitude: -0.717
        Jupiter:
          Zodiac Sign: Aquarius
          Zodiac Degree: 26.198279
          Right Ascension: 5.738048
          Declination: -0.238475
          RA (Degrees): 21 55 03.82
          Dec (Degrees): '-13 39 49.0'
          Apparent Magnitude: -2.106
        Saturn:
          Zodiac Sign: Libra
          Zodiac Degree: 4.359608
          Right Ascension: 3.227265
          Declination: 0.00641
          RA (Degrees): 12 19 38.08
          Dec (Degrees): +00 22 02.1
          Apparent Magnitude: 0.867
        Uranus:
          Zodiac Sign: Pisces
          Zodiac Degree: 22.944958
          Right Ascension: 6.175279
          Declination: -0.060838
          RA (Degrees): 23 35 16.18
          Dec (Degrees): '-03 29 08.7'
          Apparent Magnitude: 5.944
        Neptune:
          Zodiac Sign: Aquarius
          Zodiac Degree: 24.439029
          Right Ascension: 5.705164
          Declination: -0.240323
          RA (Degrees): 21 47 31.64
          Dec (Degrees): '-13 46 10.1'
          Apparent Magnitude: 7.825
        Pluto:
          Zodiac Sign: Capricorn
          Zodiac Degree: 3.166765
          Right Ascension: 4.770377
          Declination: -0.319434
          RA (Degrees): 18 13 17.39
          Dec (Degrees): '-18 18 07.9'
          Apparent Magnitude: 14.096
```

**Comment by pokrovskyy** [comment]
Thanks, I understand how to use satpoints on individual inscription level. My question is more about the global level. Eg. I need to use `separate-outputs` but want to instruct ord to use certain cardinal UTXO in the wallet. In previous versions of ord I was able to specify the satpoint as a command line argument, along with the path to batch file. Now it seems satpoint CLI argument is no longer available for batch inscribe, so how do I use `separate-outputs` while instructing ord to use a certain satpoint? (btw I was able to achieve the desired result by adjusting the assert and passing global `satpoint` in `separate-outputs` mode)

**Comment by raphjaph** [comment]
I don't think we ever had support for specifying `--satpoint` in combination with `--batch`. If you have the commit of where we changed that I'll have a look.

Specifying a satpoint means picking one single sat so it's unclear how multiple inscriptions can be on the same sat but still be in seperate outputs. Could you describe what you're trying to do exactly?

**Pull request merged**
