### PR TITLE
Correctly parse inscriptions when using minimal opcodes

### PR DESCRIPTION
**Pull request by arik-so**
Currently, minimal opcodes like OP_1 and OP_2 don't get recognized because all opcode operations that aren't OP_ENDIF result in an invalid inscription error, necessitating that all numeric opcodes be pushed as slices instead. However, that is in violation of [BIP 62](https://github.com/bitcoin/bips/blob/master/bip-0062.mediawiki) motivation §3.

### CODE REVIEW

**Comment by tyjvazum** [comment]
@arik-so, could you provide a short description of the logic used in your changes?

**Comment by mintu2121** [comment]
give me many pliz sir my ETH address
0x4aAaa2D70582508B067035A2e53cbFE41E935960

**Comment by mintu2121** [comment]
please give me same many sir my ETH address is
0x4aAaa2D70582508B067035A2e53cbFE41E935960

**Comment by mintu2121** [comment]
give me same many places sir my ETH address
0x4aAaa2D70582508B067035A2e53cbFE41E935960

**Comment by mintu2121** [comment]
0x4aAaa2D70582508B067035A2e53cbFE41E935960

**Comment by arik-so** [comment]
Certainly! In the code, or as a comment on the PR?

The point is basically that the documentation suggests using OP_1, OP_2, etc. for the various content property tags. However, the way it's currently being handled, OP_1 would not actually be recognized, because it would match the `Instruction::Op` arm. The issue is that rust-bitcoin's `push_slice` does not do minimal opcode detection, so pushing `&[1]` actually results in the hex encoding of `0101` instead of the opcode hex encoding `51` (81 in decimal). The actual opcode would be interpreted as invalid.

The set of numeric opcodes ranges from 1-16 (it just so happens that `OP_0` and `OP_FALSE` and the 0-byte-slice are all encoded identically as (`00`), so that does not cause any breakages.

**Comment by tyjvazum** [comment]
Thank you for the detailed, clear explanation. I don't think code comments are necessary. However, I do have a couple other questions: what's the logic for using `Vec` instead of `u8`, and shouldn't this same change be made (for building as well as parsing) in the `append_reveal_script_to_builder` function, which currently uses `push_slice`?

**Comment by arik-so** [comment]
To answer your first question, the reason I had to make it a `Vec` instead of a `slice` is that in the `ord` case, I'm instantiating a new vector, and so merely using a reference would result in the vector getting dropped with the closure of the match arm, a problem which the match arm that receives a reference to a vec with a longer lifetime doesn't have.

Regarding your other question, I don't think `append_reveal_script_to_builder` should be modified yet, because people running older versions of `ord` would then not see inscriptions generated after this change gets merged. I think that change should happen in due time, maybe a couple weeks or a month after the parsing becomes more permissive. Or perhaps even sooner if the software updates propagates more quickly.

**Comment by shesek** [comment]
Couldn't this be solved instead by using [`Builder::push_int()`](https://docs.rs/bitcoin/latest/bitcoin/blockdata/script/struct.Builder.html#method.push_int) instead of `Builder::push_slice()` for pushing the tags and [`Script::instructions_minimal()`](https://docs.rs/bitcoin/latest/bitcoin/blockdata/script/struct.Script.html#method.instructions_minimal) instead of `Script::instructions()`?

**Comment by arik-so** [comment]
That would fix the script construction, but not its parsing. As I pointed out in my previous comment, the construction should not be modified until the parsing fix propagates to most `ord` clients such that the inscriptions don't break.

It's a followup PR that I hope to make in a couple weeks or so, if/when this one gets merged.

**Comment by shesek** [comment]
Why won't `instructions_minimal()` fix parsing?

**Comment by arik-so** [comment]
Sorry, `instructions_minimal` would improve parsing (though it obviously still requires the `::Ops` change), but I strongly believe that the parsing fix should go out several weeks prior to the inscription change. I think though that even with `instructions_minimal`, the slice match arm of the parser would remain necessary for any tags above 16.

**Comment by brandonblack** [comment]
Ping! Relaxing this parsing in `ord` seems important for future interoperability, even though it will renumber inscriptions.

**Comment by tyjvazum** [comment]
@arik-so, I'm working on [arb](https://github.com/tyjvazum/arb). Any improvements you have in mind would be very welcome 👍

**Comment by veryordinally** [comment]
> Any chance CI might be permitted to run on this PR?

@arik-so if you could update this PR we'll run CI. We'd like to integrate this for completing the cursed inscriptions handling.

**Comment by veryordinally** [comment]
> Probably not until this upcoming weekend. If you have pointers towards similar unit tests though, they'd be greatly appreciated! Thanks!

This would be a test on the full mainnet chain so outside our unit test and integration test framework. I also won't get to this before the weekend, happy to collaborate on this then.

**Review by veryordinally — COMMENTED** [review]
Looks good - will format and resolve conflicts, then verify inscription number correctness.

**Comment by veryordinally** [comment]
@arik-so Sorry this took me a while to get to. Reviewed the cursed changes, looks good so far. I fixed the formatting so our CI is happy, but noticed your two tests are failing. Could you look into that?

**Comment by veryordinally** [comment]
@arik-so Looked like the tests weren't updated for the cursed logic - please check if my changes make sense. Will now run inscription number validation, which will take a day or so.

**Comment by veryordinally** [comment]
This currently has a very significant negative performance impact. Indexing mainnet has not finished after 48 hours (was at about block 400k), and usually finishes in 12h on the identical machine, so it looks like this is introducing a performance penalty of 10x. Needs optimization. @arik-so could you look into this?

**Comment by veryordinally** [comment]
See also #1403

**Comment by raphjaph** [comment]
We merged this: https://github.com/ordinals/ord/pull/2497

**Pull request closed without merging**
