### PR TITLE
Add font/woff2 media type with extension .woff2

### PR DESCRIPTION
**Pull request by devords**
This would make it easier for people to inscribe custom fonts.

### CODE REVIEW

**Comment by elocremarc** [comment]
Should we add more types?

**Comment by devords** [comment]
@elocremarc Are you thinking about any specific file types? AFAIK, WOFF 2.0 is the most widely accepted standard for fonts today. So, maybe makes sense to start with that and add other font types if there's any demand.

**Comment by elocremarc** [comment]
Maybe .ttf ?

**Comment by devords** [comment]
Added .otf, .ttf and .woff as well. Might as well just add them all while at it.

**Review by raphjaph — APPROVED** [review]

**Pull request merged**
