### PR TITLE
Display rune balances in address page

### PR DESCRIPTION
**Pull request by yoitsyoung**
Hi! First ever public pull request 🙏  Please feedback is welcome

Referencing issue #3809 to add more information to address page. I also refactored the tests on templates/address.rs so that different categories of address information are tested separately. 

Unfortunately, I'm not able to get the integration at tests/server.rs to work; it seems to be that rune commands are not compatible with the mockcore::spawn() handle, hence it is necessary to enforce the transaction on regtest; however I get a 404 error when requesting pages with a regtest address format; so the test currently always fails.

### CODE REVIEW

**Comment by yoitsyoung** [comment]
cc @cryptoni9n

**Review by raphjaph — CHANGES_REQUESTED** [review]
Thanks for the PR, this is great!

I've made some changes to help you along a bit. Since we are aggregating potentially the same runes in different outputs I added this rather complicated looking addition logic. Basically I create a Map with SpacedRunes to Pile (Amount) and if we have already encountered this rune in a previous output instead of inserting we add the balance on to the existing. 

The reason the tests weren't working because you forgot to add the `--index-addresses` flag to `TestServer::spawn`.

I also added the symbol next to the amount.

Some tasks for you if you'd like to refine this PR:

1. Send multiple different runes to the same address
2. Send the same rune twice to the same address (to check that different outputs are aggregated correctly)
3. We could sort the the runes lexicographically (optional)
4. Add a link (href) to the Rune name in the html so a user can click on it to go to that runes etching/parameter page.

If you have any other question, don't hesitate to ask!

**Comment by yoitsyoung** [comment]
Thanks @raphjaph! Updated as per your comments. Definitely should have thought about aggregating the Rune balances, stupid me; I didn't sort by alphabet as I thought it we'd want to keep the client as un-opinionated as possible, but feel free to do so of course.

**Review by raphjaph — APPROVED** [review]
Perfect PR!

LGTM

**Comment by yoitsyoung** [comment]
> Does this also apply to the JSON api?

I believe the address JSON-RPC endpoint only returns a list of outputs currently, @raphjaph I was thinking we can serialize the AddressHtml struct and pass it into the response?

**Pull request merged**
