### PR TITLE
added hindi translation of ordinals handbook

### PR DESCRIPTION
**Pull request by duttydeedz**
Hi @raphjaph! Have added the Hindi translation for the Ordinals handbook. Please check if everything is good, this is as per[ OMB Bounty 16B.](https://github.com/OrdinalMaxiBiz/bounties/issues/19) Thanks for your time!

### CODE REVIEW

**Comment by duttydeedz** [comment]
Hey @raphjaph just checking in about this pull request :) Plz let me know if there is anything additional i need to do?

Thanks!

**Comment by duttydeedz** [comment]
Hi @raphjaph thanks for checking, I have corrected and fixed the invalid unescape sequence error. It should merge perfectly now :)

**Comment by raphjaph** [comment]
I'm trying to fix some things like replacing some ' with ` (back ticks), but my terminal is breaking when I try to edit the text.  This is the command that should pass:
```
MDBOOK_BOOK__LANGUAGE=hi mdbook build docs -d build/hi
```
But getting: 
```
2023-10-26 11:56:29 [INFO] (mdbook::book): Book building has started
thread 'main' panicked at 'byte index 143 is not a char boundary; it is inside '।' (bytes 141..144) of `"'फ़ाइल' चयन करें -> 'New Wallet' और 'ऑर्ड' नामक एक नया वॉलेट बनाएं।`', /Users/raphael/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polib-0.2.0/src/po_file/po_file_parser.rs:277:30
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2023-10-26 11:56:29 [ERROR] (mdbook::utils): Error: The "gettext" preprocessor exited unsuccessfully with exit status: 101 status
 ```

Could you try and fix those again?

**Comment by duttydeedz** [comment]
@raphjaph thank you for checking it and giving me instructions on what to fix, I have fixed the back ticks for the full translation and also used the command : MDBOOK_BOOK__LANGUAGE=hi mdbook build docs -d build/hi
This built the mdbook successfully (please see screenshot). 
Screenshot 2023-10-26 at 4 53 18 PM

Everything looks good for the merge now 👍 appreciate your time and help!

**Comment by raphjaph** [comment]
It's not building for me and there's a bunch of unresolved merge conflicts. I think at this point it's probably best to close this PR and open a new one with the version that the screenshot is from.

**Comment by duttydeedz** [comment]
New Pull request created, closing this one.

**Pull request closed without merging**
