### PR TITLE
Update explorer.md

### PR DESCRIPTION
**Pull request by elocremarc**
Guide on how to:
run the explorer
test your inscriptions in regtest

### CODE REVIEW

**Comment by elocremarc** [comment]
Would it be more appropriate to put the regtest guide in the inscriptions.md?

**Review by veryordinally — APPROVED** [review]

**Comment by elocremarc** [comment]
@raphjaph Whats the status on this Pr?

**Comment by raphjaph** [comment]
> @raphjaph Whats the status on this Pr?

Made some comments above

**Comment by veryordinally** [comment]
> > @raphjaph Whats the status on this Pr?
> 
> Made some comments above

@raphjaph We couldn't find your comments. This looks like a useful addition to me.

**Comment by raphjaph** [comment]
Made the changes and will merge

**Pull request merged**
