### PR TITLE
use absolute links in SUMMARY.md

### LINKED ISSUE #4060: 404 issue with links on docs.ordinals.com
on initial click, many pages are returning a 404 initially, including:

https://docs.ordinals.com/inscriptions/inscriptions/metadata.html
https://docs.ordinals.com/inscriptions/inscriptions/provenance.html
https://docs.ordinals.com/inscriptions/inscriptions/rendering.html

However, clicking the link again renders the page correctly and changes the URL:

https://docs.ordinals.com/inscriptions/metadata.html
https://docs.ordinals.com/inscriptions/provenance.html
https://docs.ordinals.com/inscriptions/recursion.html

Clicking the link once again bounces back and forth between the content and the 404.

### PR DESCRIPTION
**Pull request by cryptoni9n**
fixes #4060 

from _inscriptions/delegate.md_ to **/inscriptions/delegate.md** for links under inscriptions, runes, guides and bounty folders.

### CODE REVIEW

**Review by cryptoni9n — COMMENTED** [review]
first commit didn't have the new link for spliiting.md - added with a subsequent commit but PR stuck in conflict.

**Comment by raphjaph** [comment]
The problem is something with github actions because if you run it locally it works fine. @cryptoni9n try running `just serve-docs` to see it locally. You might need to install some things, see translation section of the README

**Comment by cryptoni9n** [comment]
> The problem is something with github actions because if you run it locally it works fine. @cryptoni9n try running `just serve-docs` to see it locally. You might need to install some things, see translation section of the README

thanks Raph - have been struggling trying to get just working on my windows machine.  I believe it's installed correctly, but can't build or serve docs, keep getting:
```md

$ just --version
just 1.36.0

$ just build-docs
error: Recipe `build-docs` failed with exit code 101

$ just serve-docs
error: Recipe `build-docs` failed with exit code 101
```

**Comment by raphjaph** [comment]
Do any other just recipes work?

**Comment by raphjaph** [comment]
Otherwise try the command manually without the languages:
```
mdbook build docs -d build
python3 -m http.server --directory docs/build/html --bind 127.0.0.1 8080
```

**Comment by raphjaph** [comment]
Oh and don't try it on this branch, it doesn't work. Try `master`

**Comment by cryptoni9n** [comment]
> Do any other just recipes work?
> 
> Try `just fmt` for example

yes, that one works and shows the green dot with message "command executed x secs ago and took 1.074s":

```bash
$ just fmt
cargo fmt --all
```

If I try and run the mdbook command by itself:

```bash
$ mdbook --version
mdbook v0.4.42 

$ mdbook build docs -d build
```

it shows the red dot and says "command executed x secs ago, took 46ms and failed (Error Code 101)"

**Comment by cryptoni9n** [comment]
> Oh and don't try it on this branch, it doesn't work. Try `master`

getting all the same errors from master branch :/ 

anyway, were you saying that the github actions problem is what is causing the CI failure?  Or that it is what is causing the issue on docs.ordinals.com?

**Comment by raphjaph** [comment]
Hmm, seems to Windows stuff. 

This PR doesn't work because we need to use relative paths in the `SUMMARY.md`, see here: https://github.com/rust-lang/mdBook/blob/master/guide/src/format/summary.md

You are on the right track though that the rendered page uses relative paths incorrectly.

I'll close this for now and continue discussion in your issue

**Pull request closed without merging**
