### PR TITLE
Ensure a RUNE balance is set to 0 if it is etched with an expired deadline

### PR DESCRIPTION
**Pull request by victorkirov**
I'm still trying to wrap my head around the Runes code, so not 100% sure, but I _think_ this check is missing 👀

### CODE REVIEW

**Comment by casey** [comment]
Thank's for the PR! This check should indeed be here as is, but this code is going through a lot of flux, and I'm actually going to remove the restriction that etchers must obey the mint limits. When they do this, I'm also going to display a premine percentage on the rune page, so it's clear when the etcher has premined the token.

**Comment by victorkirov** [comment]
Ok, great. Thanks for the feedback 😄 Looking forward to seeing how this evolves

**Comment by casey** [comment]
Definitely very happy that someone is paying attention! Critical review of the low-level details is super welcome.

**Comment by victorkirov** [comment]
I see the new mint changes went in. I think this issue is still present though 👀

**Comment by casey** [comment]
Yah, definitely. The mint changes were  mostly a refactor to require a `mint` flag to be set in order to have an open mint. I'm going to remove all the limits in a follow-up PR. The follow-up PR will actually allow people to create runes that can overflow a u128, and just use saturating addition everywhere. So it's caveat emptor and on the rune creators to pick limits, either to the limit per mint, or the number of mints that are possible, that don't wind up overflowing.

**Pull request closed without merging**
