### PR TITLE
Get output information by address

### PR DESCRIPTION
**Pull request by raphjaph**

### CODE REVIEW

**Comment by lifofifoX** [comment]
@raphjaph This looks great to me, and makes sense to combine all three 💯

Do you want me to port the test here?

**Comment by raphjaph** [comment]
@lifofifoX no worries, I got it

**Comment by raphjaph** [comment]
@lifofifoX this is ready for review if you wanna have a look!

**Review by casey — APPROVED** [review]
LGTM

**Comment by lifofifoX** [comment]
Looks great, thanks Raph!

**Pull request merged**
