### PR TITLE
zh.po documents by the mdbook-i18n-helpers

### PR DESCRIPTION
**Pull request by DrJingLee**
Following #2385, 

Construct the new documents by mdbook-i18n-helpers;
Complete the Chaptor 3.
updating the remaining.

following ISO-639-1 code standard of languages:
zh = Chinese Version of Language

### CODE REVIEW

**Comment by raphjaph** [comment]
@DrJingLee I added some scaffolding and a language picker. you can see the page by installing [just](https://github.com/casey/just)
and doing 
```
just serve-docs
```

or if you do not want to install just it would be:
```
  mdbook build docs -d build
  MDBOOK_BOOK__LANGUAGE=zh mdbook build docs -d build/zh
  mv docs/build/zh/html docs/build/html/zh
  python3 -m http.server --directory docs/build/html --bind 127.0.0.1 8080
```

**Comment by raphjaph** [comment]
And .pot files are autogenerated so they do not have to be checked into git :)

**Comment by raphjaph** [comment]
It also seems that it's only partially translated: 
Screenshot 2023-08-30 at 21 23 58

**Comment by raphjaph** [comment]
I've delete the changes I made and opened a new PR https://github.com/ordinals/ord/pull/2403 for just the language picker things. Once that is merged you can merge those changes in here

**Comment by raphjaph** [comment]
I just merged https://github.com/ordinals/ord/pull/2403, so have a look at the updated [README](https://github.com/ordinals/ord#translations) for instructions.

For this PR I will integrate into our build system tomorrow :)

**Comment by DrJingLee** [comment]
> I just merged https://github.com/ordinals/ord/pull/2403, so have a look at the updated [README](https://github.com/ordinals/ord#translations) for instructions.
> 
> 
> 
> For this PR I will integrate into our build system tomorrow :)

Great job @raphjaph 👍👍

**Pull request closed without merging**
