### PR TITLE
Documentation Spanish(ES)

### PR DESCRIPTION
**Pull request by NNull13**
Hello :D

### CODE REVIEW

**Comment by raphjaph** [comment]
This is a great start but unfortunately this is not in the correct format for https://github.com/ordinals/ord/issues/2385. You can view how the docs look with  mdbook serve docs --open. It should have a language switch button on the top right like seen here: https://google.github.io/comprehensive-rust/index.html

**Comment by Isabelfoxenduke** [comment]
> This is a great start but unfortunately this is not in the correct format for #2385. You can view how the docs look with mdbook serve docs --open. It should have a language switch button on the top right like seen here: https://google.github.io/comprehensive-rust/index.html

Thanks for input Raph!

**Comment by Isabelfoxenduke** [comment]
> This is a great start but unfortunately this is not in the correct format for https://github.com/ordinals/ord/issues/2385. You can view how the docs look with  mdbook serve docs --open. It should have a language switch button on the top right like seen here: https://google.github.io/comprehensive-rust/index.html

Hi Raph - just for clarity - does this mean it is not possible to merge translation PRs until the mdbook language switch feature is implemented?

**Comment by raphjaph** [comment]
I'm working on that now, will merge that today

**Comment by raphjaph** [comment]
I'm working on that now, will merge that today

**Comment by raphjaph** [comment]
I just merged https://github.com/ordinals/ord/pull/2403, so have a look at the updated [README](https://github.com/ordinals/ord#translations) for instructions.

**Comment by raphjaph** [comment]
I just merged https://github.com/ordinals/ord/pull/2403, so have a look at the updated [README](https://github.com/ordinals/ord#translations) for instructions.

**Comment by raphjaph** [comment]
Thanks but we decided to go with this translation: https://github.com/ordinals/ord/pull/2448

**Pull request closed without merging**
