### PR TITLE
Index inscriptions by address

### PR DESCRIPTION
**Pull request by markovichecha**
Added an address to inscriptions index and address endpoint with inscriptions. Resolves: #2619 

image

Address index relies on transactions index, how should we handle this? Fail to startup if there are no --index-transactions flag?

### CODE REVIEW

**Comment by markovichecha** [comment]
@raphjaph *actively harassing to check on this PR as were suggested on stream*, thanks

**Comment by ynohtna92** [comment]
> Address index relies on transactions index, how should we handle this? Fail to startup if there are no --index-transactions flag?

I don't think it should fail, I implemented the address index onto my own branch a while ago without the transaction index. Users shouldn't need to double up on storing tx information as it is already done with -txindex.

Perhaps use it if it is available otherwise use the rpc getTransaction.

https://github.com/ynohtna92/ord-litecoin/blob/30825f67ccca4921c8f96e6a7d212cd3660f1f70/src/index/updater/inscription_updater.rs#L413-L419

**Comment by Klyaus** [comment]
Hello! I’m experimenting with your version when indexing testnet (I launched Ord in Docker with the command “ord --data-dir /index-data --index-transactions --index-addresses server”). And I encountered this behavior:
```
[2024-04-18T11:37:24Z INFO  ord::index::updater] Block 2441766 at 2023-07-14 03:35:26 UTC with 21 transactions…
[2024-04-18T11:37:24Z INFO  ord::index::updater] Block receiver disconnected: sending on a closed channel
[2024-04-18T11:37:24Z INFO  ord::index] script is not a p2pkh, p2sh or witness program
[2024-04-18T11:37:24Z WARN  ord::subcommand::server] Updating index: script is not a p2pkh, p2sh or witness program
```
after that, the indexer starts scanning a few days before the specified date, and again hits the same block, and so on in a circle. Have you seen this kind of behavior?

**Comment by markovichecha** [comment]
Hey @Klyaus. I haven't met this error, but may be it was due to not indexing mainnet till the end. I'll return to this PR soon and will change transaction index behavior and try to fix this issue.

**Comment by Klyaus** [comment]
> Hey @Klyaus. I haven't met this error, but may be it was due to not indexing testnet. I'll return to this PR soon and will change transaction index behavior and try to fix this issue.

Great! Thanks for the answer. I also think this is due to the fact that this is a testnet.

**Comment by raphjaph** [comment]
We recently merged #3757, which adds a more comprehensive address to output tracker. If you look at it you'll see the html page is just a list of outputs. If you want you could add more descriptive and aggregated information like inscriptions, btc, sats and runes. Also your PR links addresses we show in places to the address html page. If you feel like you could probably use some of the work you did here and just build on top of what I coded up. Best to chunk these up into different PRs. Let me know if you're up for that :)

**Pull request closed without merging**
