### PR TITLE
Add balances data into rune info

### PR DESCRIPTION
**Pull request by lugondev**
LugonShot 2024-01-31 at 14 11 30@2x

- Add balances data into rune info

### CODE REVIEW

**Comment by datnddot** [comment]
Nice move 👍

**Comment by 0xTigerbao** [comment]
nice nice nice.... 🧨

**Comment by lugondev** [comment]
LugonShot 2024-01-31 at 22 04 35@2x

👯

**Comment by lugondev** [comment]
@raphjaph @casey help me review this PR

thanks

**Comment by lugondev** [comment]
I hope this pull request will appear in the next release.

**Comment by raphjaph** [comment]
The call to `rune_balances` is very inefficient. We would need to add a multimap table called RUNE_TO_OUTPOINTS. This gets into the guts of the database but you can take a stab at it if you want :)

**Comment by lugondev** [comment]
I think users really want to see specific rune's balance. 
Hope you can review my Pr again

**Comment by casey** [comment]
We cannot merge this as-is. The code as written loads every output with a rune balance from the database. With any nontrivial amount of runes, this will take an extreme amount of compute and RAM, and would be a DoS vector.

To make this efficient enough to be safe, we would need to add a rune -> outpoint balance map which is updated whenever an outpoint is spent or a new outpoint is created.

**Comment by lugondev** [comment]
oh, got it.

**Comment by svensei** [comment]
!wen // really excited about this feature tbh

**Pull request closed without merging**
