### PR TITLE
Add prettier config

### LINKED ISSUE #1586: Add prettier config/ignore
I was looking to correct some typos in the docs, but I have prettier enabled on save and it suggests more changes than I intended to include in the PR.

I can disable it and restart my editor, but it'd be nice if the behavior were instead defined similar to [rustfmt.toml](https://github.com/casey/ord/blob/master/rustfmt.toml) at the root.

**Option A** - add a prettier config for the docs

- add `.prettierignore` at the root to exclude all folders except docs
- add `.prettierrc.toml` in the docs folder
  - tabWidth = 2
  - useTabs = false
  - singleQuote = false
  - printWidth = 100
- run `prettier --write` to format all markdown in /docs one-time
- encourage future commits to use prettier

**Option B** - add a general ignore statement for prettier

- add `.prettierignore` at the root to exclude all folders

I'm happy to open a PR for either option!

### PR DESCRIPTION
**Pull request by whoabuddy**
This PR updates the main ignore file so it includes `/docs`, and adds a basic toml config in that folder based on the [rustfmt.toml settings](https://github.com/casey/ord/blob/master/rustfmt.toml).

It also adds a prettier action to the lint step in the CI - the configuration looked straight-forward but definitely want to verify it runs as expected.

Fixes #1586

### CODE REVIEW

**Comment by whoabuddy** [comment]
This should be ready to go. I moved the prettier action up to the docs job (my eyes originally gravitated to lint), and it runs before the docs are built. It should respect the configurations in the repo and this PR will be a good test. 

Current state via `prettier -c .` at the root:

```
Checking formatting...
[warn] docs/src/bounties.md
[warn] docs/src/bounty/0.md
[warn] docs/src/bounty/1.md
[warn] docs/src/bounty/2.md
[warn] docs/src/bounty/3.md
[warn] docs/src/contributing.md
[warn] docs/src/digital-artifacts.md
[warn] docs/src/donate.md
[warn] docs/src/faq.md
[warn] docs/src/guides.md
[warn] docs/src/guides/collecting.md
[warn] docs/src/guides/explorer.md
[warn] docs/src/guides/inscriptions.md
[warn] docs/src/guides/moderation.md
[warn] docs/src/guides/sat-hunting.md
[warn] docs/src/inscriptions.md
[warn] docs/src/introduction.md
[warn] docs/src/overview.md
[warn] docs/src/SUMMARY.md
[warn] Code style issues found in 19 files. Forgot to run Prettier?
```

**Comment by casey** [comment]
We should only add a CI job if it has no warnings or errors. Can you format in this PR so it's a clean run on CI?

**Comment by whoabuddy** [comment]
Yes looks like it wants to commit those changes back and is unable, now that the CI will run I can make sure it passes and let you know when this is ready.

**Comment by casey** [comment]
I'd like to avoid CI jobs that make commits, since that can be confusing. Can you configure it to error-only on CI issues?

**Comment by whoabuddy** [comment]
The update in 035f9d1 should make it so that it fails on check, can you run it again?

Then I can write the changes in a separate commit to test it passing as well.

**Comment by whoabuddy** [comment]
Well looks like that action doesn't work as expected, when I saw it fail originally I thought it worked but looking closer there's an error that prettier isn't installed.

first run 248bd8e

```
Prettifying files...
Files:
/home/runner/work/_actions/creyD/prettier_action/v4.2/entrypoint.sh: line 74: prettier: command not found
Problem running prettier with --check .
Error: Process completed with exit code 1.
```

Second run after updating the files in c60f519, same thing:

```
Installing prettier...
Prettifying files...
Files:
/home/runner/work/_actions/creyD/prettier_action/v4.2/entrypoint.sh: line 74: prettier: command not found
Problem running prettier with --check .
Error: Process completed with exit code 1.
```

My guess is it's an issue in the action itself, there were a handful to choose from but at this point it's probably good to take a temp check: do you think this is still needed for the repo, or would a one-time cleanup suffice?

**Comment by whoabuddy** [comment]
Confirmed it was a bug on their side, the latest version 4.3 is running prettier but the results are different from what I get locally. My guess is it's not using or honoring the config file for some reason.

Locally, whether I use the global prettier or npx:

```
> npx prettier -c .
Checking formatting...
[warn] docs/src/inscriptions.md
[warn] Code style issues found in the above file. Forgot to run Prettier?
```

In the [CI / docs action](https://github.com/casey/ord/actions/runs/4242529590/jobs/7374153611):

```
Installing prettier...
Prettifying files...
Files:
Checking formatting...
All matched files use Prettier code style!
Prettier result: 0
```

Happy to keep at it if it still makes sense for the repo, or we can close this and I'll submit a new PR with the updated formatting and we just go from there.

**Comment by whoabuddy** [comment]
Checking in on the comments above, if this still interests you happy to give it another try, or we can just format the files one-time in a separate PR and keep moving.

**Comment by raphjaph** [comment]
This is nice but I don't think we need this anymore

**Pull request closed without merging**
