### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by dude513**
Adding dependencies notes in README.md.
Reference: https://github.com/casey/ord/issues/1430.

### CODE REVIEW

**Review by casey — CHANGES_REQUESTED** [review]
Thanks for the PR!

I'd rather not suggest upgrading ubuntu, since that's a big step that might break a user's system. For a first step, I'd like to just document the GLIBC version required, and if it's possible to install it, provide instructions for just installing the right version.

Also, we have a "building" section, so it's probably better to include this info there.

**Comment by casey** [comment]
Feel free to reuse this PR and just modify it!

**Comment by dude513** [comment]
> Feel free to reuse this PR and just modify it!

On my way.

**Comment by dude513** [comment]
I'm not sure if we need an instruction on how to install Glibc from source, please tell me if we should remove it: https://github.com/casey/ord/pull/1556/commits/6d6d3afa3091cc8cb5eee3ea1d8df86c20d9c57a.

**Review by casey — CHANGES_REQUESTED** [review]
I think we should probably remove the glibc-from-source instructions. If someone doesn't have the right version, the best thing is probably to figure out how to upgrade their OS, or use their OS's provided way of installing glibc.

**Comment by dude513** [comment]
> I think we should probably remove the glibc-from-source instructions. If someone doesn't have the right version, the best thing is probably to figure out how to upgrade their OS, or use their OS's provided way of installing glibc.

You have mentioned that upgrading is not safe to recommend to users, likewise there is no "OS's provided way of installing glibc", but only compiling from source. For example on Ubuntu 20 `apt-cache policy libc6` the candidate version is `2.31-0ubuntu9.9`.

I left a comment here https://github.com/casey/ord/issues/1430#issuecomment-1425434981, this is something I would rather use, or the only option left is to say what glibc version is required and let users to figure out how to upgrade it.

**Comment by raphjaph** [comment]
This is probably fixed by upgrading Ubuntu now.

**Pull request closed without merging**
