### PR TITLE
Make inscriptions module pub

### PR DESCRIPTION
**Pull request by raphjaph**
Made the `inscriptions` module and some structs `pub`. Did it in a pretty haphazard way and would love feedback if I should use `pub use` in `src/inscriptions.rs` so that there is less indirection (less submodules to include in the import statements). Basically any feedback on good crate/library design.

 Let me know if this is useful to you guys @rot13maxi @JeremyRubin

### CODE REVIEW

**Comment by JeremyRubin** [comment]
I think you should split out things into a couple different crates -- inscription for example should be really "tiny" to make it includable in Miniscript as an optional dep.

**Comment by raphjaph** [comment]
Ok thanks for the feedback! I think splitting out into crates makes sense but probably a bit too much work for the next release. 

Possible sub crates:

- `ordinals`/`sats`
- `inscriptions`
- `runes`
- `wallet`
- `ord` (binary crate)

**Comment by casey** [comment]
What functionality would a crate need to expose for use in miniscript in order to be useful?

**Comment by JeremyRubin** [comment]
i doubt mainline miniscript will

1) take a non-rust-bitcoin-owned dep
2) add inscriptions to the spec, as I've done in Sapio

That said, were you to get buy in, the functionality is basically just what's in the inscription module, which is pretty minimal.

**Comment by raphjaph** [comment]
I'm going to close this since we are working on #3079 and #1249.

**Pull request closed without merging**
