### PR TITLE
Batch inscriptions

### PR DESCRIPTION
**Pull request by raphjaph**
`ord wallet batch-inscribe inscriptions.yaml`

`inscriptions.yaml` should include:
- [x] path to files
- [x] metadata to include for each file
- [x] should set parent
- [x] fee-rate

Additional cool stuff:
- [ ] destination
- [ ] chain commit/reveal if a single transaction over size limit
- [ ] save state of batch in `state.yaml`

### CODE REVIEW

**Comment by goodwinmark** [comment]
👁

**Comment by raphjaph** [comment]
@casey, @terror, @veryordinally this is ready for an initial review.

I wrote some high-level integration tests, but still need a lot of unit tests.

Additionally, I haven't yet implemented the different modes.

**Comment by dannydeezy** [comment]
could this eventually support choosing which satpoints to inscribe on for each of the inscriptions in the batch?

**Comment by raphjaph** [comment]
yeah for sure! Want to keep it as simple as possible for now but we can do really cool stuff with this

**Review by khademreza688 — APPROVED** [review]

**Comment by raphjaph** [comment]
TODO:
- [ ] parent info should contain inscription id
- [ ] conflicting flags tests
- [ ]

**Review by casey — APPROVED** [review]
WHY NOT

**Pull request merged**
