### PR TITLE
Enable redb's new quick-repair mode

### PR DESCRIPTION
**Pull request by partialord**
This enables redb's new quick-repair mode so you can try it out.  It's using redb master, since this version hasn't been released yet.

Recovery after a crash always means rolling back to the last complete commit; if that commit was made with quick-repair enabled, then recovery will be instant.  So to get the new behavior, you'll need to let it make one successful commit with the new code before you start making it crash.  After that, no matter what you do, you should never have to wait for repair again.  You can tell it's working because it won't print the "Index file needs recovery" message, even after a crash; it'll just look like a normal clean startup.

Quick-repair mode needs to save the database allocator state with each commit, which costs about 200 ms per commit for a 190 GB database (it scales linearly with file size).  My guess is that's totally fine, so for now quick-repair is unconditionally enabled for all writes to the database.

If you try this out, let me know how it goes!

### CODE REVIEW

**Comment by casey** [comment]
Very nice! I just deployed it to charlie for testing.

**Comment by casey** [comment]
Just tried it out by `kill -9`'ing ord a bunch. Works like a charm!

**Comment by Luigi-1Combo** [comment]
It is best to add a parameter "enable-quick-repair" to ord, which can be turned off when synchronizing from the beginning to increase the speed, and can be turned on after synchronizing to the latest height.

**Review by raphjaph — APPROVED** [review]

**Comment by casey** [comment]
> It is best to add a parameter "enable-quick-repair" to ord, which can be turned off when synchronizing from the beginning to increase the speed, and can be turned on after synchronizing to the latest height.

We could add that, but only if enabling quick repair is significantly slower, which it might not be, if it's a per-commit overhead, and our commits are large and slow. So we'd need to benchmark to know the speed difference.

**Comment by casey** [comment]
@partialord reports that the overhead is pretty small: 4ms per commit for a database under 4 GB, and 200ms per commit for a 190 GB database. Building with the default options, total overhead should be about 1.5 seconds, and for a full index (sats, runes, etc) it would be a about a minute, which doesn't seem like enough to justify adding a new flag.

**Comment by twosatsmaxi** [comment]
this is good, nice. Thanks @partialord. Gone are the days where it takes hours to repair.

**Comment by cryptoni9n** [comment]
love to see major improvements like this - big thanks to @partialord and the rest of the team!

**Pull request merged**
