### PR TITLE
Add sat values to address response (#3809)

### PR DESCRIPTION
**Pull request by cryptoquick**
Returns the sat value of each individual output in the address response. See issue: #3809

### CODE REVIEW

**Comment by cryptoquick** [comment]
Not sure how this test failure is related...
https://github.com/ordinals/ord/actions/runs/12012245784/job/33483021419?pr=4101#step:5:721

**Comment by raphjaph** [comment]
I think that was just an intermittent failure.

**Comment by raphjaph** [comment]
We already have the `sat_balance` so I'm unsure what this would gives us. I think by sats I meant rare sats (sats tracked by ord).

**Comment by cryptoquick** [comment]
Sure, this just returns the sat value of each individual UTXO, since we already have that information, it's just all added together currently. Does that makes sense?

**Comment by zk-bits** [comment]
Getting individual utxo values would be super helpful and mimics esplora more closely @raphjaph

**Comment by raphjaph** [comment]
This is what the `/outputs/<ADDRESS>` endpoint is for. The `/address/<ADDRESS>` endpoint should only show aggregated information.

**Comment by cryptoquick** [comment]
We're currently running ord 0.21.0 in production, and that endpoint doesn't seem to be working. Locally against regtest I see it working on 0.21.3. Is that API new, or do you think our server might be misconfigured?

**Comment by cryptoquick** [comment]
Ah, I see in the release notes this new outputs API just came out last month in 0.21.3. Thanks, that should do just fine!

**Comment by raphjaph** [comment]
Perfect!

**Pull request closed without merging**
