### PR TITLE
Implement /r/blockinfo

### PR DESCRIPTION
**Pull request by jerryfane**
Fix issue #3065

### CODE REVIEW

**Comment by elocremarc** [comment]
I think the `inscriptions` will probably be need to be discused. If we were to add it it would probaly need pagination like with the children and sat endpoint. Each block could have hundreds or thousands of inscriptions. 

Also what happens if there is not a `next_block_hash` because we are at the current height. Or what happens if there is a reorg and an inscription changes.

**Comment by jerryfane** [comment]
Yes I agree for the inscriptions field. 

If there is no Next block, then next_block is null.
Ord already handles re-orgs.

**Review by raphjaph — APPROVED** [review]
LGTM!

We removed the inscriptions field for now, we can always add it later with proper pagination

**Comment by casey** [comment]
Nice! Added more info, docs, and tests.

**Pull request merged**
