### PR TITLE
GITBOOK: Jinglee's May 30 changes Handbook_CHN Version 1.0

### PR DESCRIPTION
**Pull request by DrJingLee**
Updated to 5-30 with the new donation address.

### CODE REVIEW

**Comment by raphjaph** [comment]
Thanks for translating! Would be great to have this as part of the normal docs, which are made with [mdBook](https://github.com/rust-lang/mdBook). In order to do that we would probably have to use https://github.com/google/mdbook-i18n-helpers. Unfortunately I do not have time to do that at the moment but happy to review the PR when it's done.

**Comment by DrJingLee** [comment]
> Thanks for translating! Would be great to have this as part of the normal docs, which are made with [mdBook](https://github.com/rust-lang/mdBook). In order to do that we would probably have to use https://github.com/google/mdbook-i18n-helpers. Unfortunately I do not have time to do that at the moment but happy to review the PR when it's done.

Thanks Raphjaph for the response. Let me try to learn how to use mdBook lol

**Comment by veryordinally** [comment]
@DrJingLee since we're getting more PRs with translations now with the OMB bounties, I was checking the status of your PR for the Chinese translation. Is there a more recent one, or what was the reason for closing? We should make sure all translations follow a common pattern.

**Comment by DrJingLee** [comment]
Yes ser,I have submitted a new PR 2350 with the mdbook format. So I close this pr and open the following pr #2350

https://github.com/ordinals/ord/pull/2350#issue-1860410815

> @DrJingLee since we're getting more PRs with translations now with the OMB bounties, I was checking the status of your PR for the Chinese translation. Is there a more recent one, or what was the reason for closing? We should make sure all translations follow a common pattern.

**Pull request closed without merging**
