### PR TITLE
Add wallet generate command

### PR DESCRIPTION
**Pull request by bingryan**
## Description

add `ord wallet generate ` command to init personal account. not only for ordinals, but also for  BTC user.

## User Story

- As a developer, I don’t like to go to a third-party wallet to generate my wallet 
- As a developer, I can generate `mainnet`, `testnet`,`signet`, `regtest` accounts through the terminal, especially the `testnet`

## Usage

```
Usage: ord wallet generate [OPTIONS]

Options:
  -p, --passphrase <PASSPHRASE>  Use <PASSPHRASE> to derive wallet seed. [default: ]
  -w, --words <WORDS>            The number of words in the phrase to generate [default: 12]
  -n, --network <NETWORK>        Specify network [default: mainnet] [possible values: mainnet, testnet, signet, regtest]
  -h, --help                     Print help
```

## Example

> ord wallet generate -n testnet

```json
{
  "mnemonic": "glimpse flavor extra labor hunt flower rate fatal cruise horror answer story",
  "passphrase": "",
  "wallet": {
    "Native Segwit(P2WPKH)": {
      "address": "tb1qlntuuzdf0uqxfxz79vt4sctqvlcgsce0fyutp3",
      "path": "m/84'/0'/0'/0/0",
      "WIF": "cQVnS53ncgNxo5ms3cbZHPHQ5wFvtABjU5pxS3ySBqpXuPfCGTtJ",
      "public_key": "028ba15b36ac98f530a66b31292a7ae5cf38bf678e6eaf34101abdb6e1b119ed9e",
      "private_key": "cQVnS53ncgNxo5ms3cbZHPHQ5wFvtABjU5pxS3ySBqpXuPfCGTtJ"
    },
    "Nested Segwit(P2SH-P2WPKH)": {
      "address": "2N4jTthyVZx4Cws7reATqbewjxJXW1ZfYkn",
      "path": "m/49'/0'/0'/0/0",
      "WIF": "cR2ALxP8nSQysDt99fmiAUrEcJMychr1Cmw49utLw7MkXpVYHD1G",
      "public_key": "03fc1d77641e23f0f0100020f040916a98d0fad2f8ecb0e0ccf1b0a799d1ef69bd",
      "private_key": "cR2ALxP8nSQysDt99fmiAUrEcJMychr1Cmw49utLw7MkXpVYHD1G"
    },
    "Taproot(P2TR)": {
      "address": "tb1ptw5dqct92rqg877m6sk5x2em9xd3lvrgf5ymua2tawk4plxm7ctsxy9thy",
      "path": "m/86'/0'/0'/0/0",
      "WIF": "cVTADsxQosEwWk4fbu8neFTyT3kjiNesD3rx3pm9DwWSYuej9SwB",
      "public_key": "022f87b1d5f23d61bb5c0160ee01195e5d1dae8085337d2ffb5a663a85af24e5c5",
      "private_key": "cVTADsxQosEwWk4fbu8neFTyT3kjiNesD3rx3pm9DwWSYuej9SwB"
    },
    "Legacy(P2PKH)": {
      "address": "n19cwnXPJj2Ukm6Y6saHM1JYL9Ds5WLFj7",
      "path": "m/44'/0'/0'/0/0",
      "WIF": "cNeXRYq735mn3VkWEx3c7bQjW5jsY9kZH6N8HrscNyxijiFReVhi",
      "public_key": "0335388edbed94ca753b67202b598995cd335050790eada2a2a3724a645903781a",
      "private_key": "cNeXRYq735mn3VkWEx3c7bQjW5jsY9kZH6N8HrscNyxijiFReVhi"
    }
  }
}
```

### CODE REVIEW

**Comment by bingryan** [comment]
@casey @raphjaph code review, plz :)

**Comment by casey** [comment]
I'm not sure I understand what the use case is here. Is it just to be a replacement for `bitcoin-cli createwallet`? Does it have additional functionality?

**Comment by bingryan** [comment]
> * testnet

This may be a more human beings command. 

this command is very useful when you need a temporary account when switching between various networks.

**Comment by bingryan** [comment]
> I'm not sure I understand what the use case is here. Is it just to be a replacement for `bitcoin-cli createwallet`? Does it have additional functionality?

This may be a more human beings command.

this command is very useful when you need a temporary account when switching between various networks.

**Comment by bingryan** [comment]
Of course, it can also be used as an generate command for a personal wallet. But that wasn't my original purpose. my initial purpose was to generate a temporary account for testing

**Comment by raphjaph** [comment]
I don't think we want to become a wrapper around `bitcoin-cli`. This command is also confusing for users since it generates non-ordinal wallets. They will do `ord wallet generate` instead of `ord wallet create`, then send ordinals to the non-ordinal wallet and lose their inscriptions to fees.

**Comment by casey** [comment]
I think I agree with Raph here. If `ord` has an `ord wallet generate` command, but it doesn't generate `ord`-compatible wallets, I think users will be very confused.

**Pull request closed without merging**
